lane :test do
  rm_derived_data(derived_data: '/Users/xiongzenghui/Library/Developer/Xcode/DerivedData')

  rm_derived_data(
    xcodeproj: '/Users/xiongzenghui/Desktop/DemoHaha/DemoHaha.xcodeproj',
    scheme: 'DemoHaha'
  )

  rm_derived_data(
    xcodeproj: '/Users/xiongzenghui/Desktop/DemoHaha/DemoHaha.xcodeproj',
    scheme: 'DemoHaha',
  )

  rm_derived_data(
    workspace: '/Users/xiongzenghui/ios_projects/osee2unified/osee2unified/osee2unified.xcworkspace',
    scheme: 'osee2unifiedRelease'
  )

  rm_derived_data(
    workspace: '/Users/xiongzenghui/ios_projects/osee2unified/osee2unified/osee2unified.xcworkspace',
    scheme: 'osee2unifiedRelease',
    module_cache_noindex: true
  )
end